select * from employees;
select * from jobs;
select * from job_history;
select * from countries;
select * from regions; 
select * from departments;
select * from locations;

--1
SELECT E.last_name, E.salary FROM employees E
INNER JOIN jobs j using (job_id)
WHERE j.job_title IN ('Sales Representative', 'Stock Clerk'); 

--2
SELECT C.COUNTRY_NAME, R.REGION_NAME
FROM COUNTRIES C
INNER JOIN REGIONS R USING (REGION_ID);

--3
SELECT D.DEPARTMENT_NAME, E.LAST_NAME
FROM DEPARTMENTS D
LEFT OUTER JOIN EMPLOYEES E
ON D.MANAGER_ID = E.EMPLOYEE_ID;

--4
SELECT E.FIRST_NAME, E.LAST_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D USING (DEPARTMENT_ID)
INNER JOIN LOCATIONS L USING (LOCATION_ID)
WHERE CITY LIKE 'S%';

--5
SELECT E.LAST_NAME, E.JOB_ID, M.LAST_NAME, M.JOB_ID
FROM EMPLOYEES E
LEFT OUTER JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID;

--6
SELECT D.DEPARTMENT_NAME, E.FIRST_NAME, E.LAST_NAME
FROM DEPARTMENTS D
LEFT OUTER JOIN EMPLOYEES E
ON D.MANAGER_ID = E.EMPLOYEE_ID;

--7
SELECT E.LAST_NAME, J.JOB_ID, J.START_DATE, J.END_DATE
FROM EMPLOYEES E
LEFT OUTER JOIN JOB_HISTORY J USING (EMPLOYEE_ID);