SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM COUNTRIES;
SELECT * FROM LOCATIONS;
SELECT * FROM JOB_HISTORY;

--1
SELECT DEPARTMENT_ID FROM DEPARTMENTS
MINUS
SELECT DEPARTMENT_ID FROM EMPLOYEES
WHERE UPPER (JOB_ID) LIKE '%CLERK%';
-- "UPPER" coloca as variaveis em maiusculo

--2
SELECT COUNTRY_ID FROM COUNTRIES
MINUS
SELECT COUNTRY_ID FROM LOCATIONS
WHERE LOCATION_ID IN
    (SELECT LOCATION_ID FROM DEPARTMENTS);
    
--3
SELECT COUNTRY_ID, COUNTRY_NAME FROM COUNTRIES
WHERE COUNTRY_ID IN
    (SELECT COUNTRY_ID FROM COUNTRIES
    MINUS
    SELECT COUNTRY_ID FROM LOCATIONS
    WHERE LOCATION_ID IN
        (SELECT LOCATION_ID FROM DEPARTMENTS));

--4
SELECT EMPLOYEE_ID, DEPARTMENT_ID FROM EMPLOYEES
INTERSECT
SELECT EMPLOYEE_ID, DEPARTMENT_ID FROM JOB_HISTORY;

--5
SELECT EMPLOYEE_ID FROM EMPLOYEES
WHERE EMPLOYEE_ID IN
    (SELECT MANAGER_ID FROM EMPLOYEES)
UNION
SELECT MANAGER_ID FROM DEPARTMENTS
WHERE MANAGER_ID IS NOT NULL
ORDER BY EMPLOYEE_ID ASC;

--6
SELECT EMPLOYEE_ID FROM EMPLOYEES
WHERE EMPLOYEE_ID IN
    (SELECT MANAGER_ID FROM EMPLOYEES)
INTERSECT
SELECT MANAGER_ID FROM DEPARTMENTS
WHERE MANAGER_ID IS NOT NULL
ORDER BY EMPLOYEE_ID ASC;

--7
SELECT EMPLOYEE_ID FROM EMPLOYEES
WHERE EMPLOYEE_ID IN
    (SELECT MANAGER_ID FROM DEPARTMENTS)
MINUS
SELECT MANAGER_ID FROM EMPLOYEES
ORDER BY EMPLOYEE_ID ASC;

--8
SELECT EMPLOYEE_ID, JOB_ID FROM EMPLOYEES
INTERSECT
SELECT EMPLOYEE_ID, JOB_ID FROM JOB_HISTORY;