UPDATE USER1.FUNCIONARIO SET SURNAME = 'Camilo' WHERE ID = 2;

COMMIT;

UPDATE USER1.FUNCIONARIO SET SURNAME = 'Carlos' WHERE ID = 1;

--T1
SELECT * FROM USER1.PRODUTOS;

--T3
UPDATE USER1.PRODUTOS SET QUANTIDADE = QUANTIDADE -1 WHERE ID = 1;

--T5
--Falha no comando
COMMIT;

SELECT * FROM USER1.PRODUTOS FOR UPDATE;