UPDATE USER1.FUNCIONARIO SET SURNAME = 'Arnaldo' WHERE ID = 1;

COMMIT;

UPDATE USER1.FUNCIONARIO SET SURNAME = 'Goulart' WHERE ID = 1;

--T1
SELECT * FROM USER1.PRODUTOS;

--T2
UPDATE USER1.PRODUTOS SET QUANTIDADE = QUANTIDADE -1 WHERE ID = 1;

--T4
COMMIT;