CREATE TABLE FUNCIONARIO(
    ID NUMBER(6),
    NAME VARCHAR2(20),
    SURNAME VARCHAR2(20),
    PRIMARY KEY (ID)
);

INSERT INTO FUNCIONARIO VALUES (1,  'João', 'Carlos');

SELECT * FROM FUNCIONARIO;

COMMIT;

INSERT INTO FUNCIONARIO VALUES (2,  'Julia', 'Maria');

ROLLBACK;

DELETE FROM FUNCIONARIO;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUNCIONARIO TO USER2, USER3;
GRANT SELECT, UPDATE ON PRODUTOS TO USER2, USER3;

CREATE TABLE PRODUTOS(
    ID INT PRIMARY KEY,
    QUANTIDADE INT CHECK (QUANTIDADE >= 0)
);

INSERT INTO PRODUTOS VALUES (1, 1);

SELECT * FROM USER1.PRODUTOS;

UPDATE USER1.PRODUTOS SET QUANTIDADE = 1 WHERE ID = 1;