CREATE TABLE EMP(
    EPM_ID INT PRIMARY KEY,
    NOME VARCHAR2(30),
    SALARIO NUMBER(8, 2) );

SELECT * FROM USER1.FUNCIONARIO;

INSERT INTO USER1.FUNCIONARIO VALUES (4, 'Falseal', 500);
UPDATE USER1.FUNCIONARIO SET SALARIO = 400 WHERE COD_FUNC = 4;

COMMIT;

GRANT SELECT ON EMP TO USER1;
REVOKE ALL ON EMP FROM USER1;