--permite a execução dos scripts de escrita
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

--1
--Criação do usuário user1
CREATE USER user1 
IDENTIFIED BY usuario1
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 5M ON USERS;

--Elimina o user1 e seus dados
DROP USER user1 CASCADE;

CREATE USER user2
IDENTIFIED BY usuario2
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

ALTER USER USER2 QUOTA 5M ON USERS;

--2
GRANT CREATE SESSION, CREATE TABLE TO USER1;

DROP USER TESTE CASCADE;
CREATE USER TESTE
IDENTIFIED BY teste;

GRANT CREATE SESSION TO TESTE;
--REVOKE ... FROM

DESC DBA_USERS;
SELECT * FROM DBA_USERS;

--3
DROP ROLE ADMIN1;

CREATE ROLE ADMIN1;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO ADMIN1;

GRANT ADMIN1 TO USER2;  

--4
--Feito
--5
--Feito