CREATE TABLE REGIAO(
    ID_REGIAO INT NOT NULL,
    NOME_REGIAO VARCHAR2(50) NOT NULL,
    PRIMARY KEY(ID_REGIAO)
);

CREATE TABLE UF(
    ID_UF INT NOT NULL,
    NOME_UF VARCHAR2(50) NOT NULL,
    ID_REGIAO INT NOT NULL,
    PRIMARY KEY(ID_UF),
    FOREIGN KEY (ID_REGIAO) REFERENCES REGIAO (ID_REGIAO)
);

CREATE TABLE MUNICIPIO(
    ID_MUNICIPIO INT NOT NULL,
    NOME_MUNICIPIO VARCHAR2(50) NOT NULL,
    ID_UF INT NOT NULL,
    PRIMARY KEY(ID_MUNICIPIO),
    FOREIGN KEY (ID_UF) REFERENCES UF (ID_UF)
);

CREATE TABLE PARTIDO(
    NUMERO_PARTIDO INT NOT NULL,
    SIGLA_PARTIDO VARCHAR2(10) NOT NULL,
    NOME_PARTIDO VARCHAR2(50) NOT NULL,
    PRIMARY KEY (NUMERO_PARTIDO)
);

CREATE TABLE VOTOS(
    ID_MUNICIPIO INT NOT NULL,
    NUMERO_PARTIDO INT NOT NULL,
    VOTOS INT NOT NULL,
    PRIMARY KEY (ID_MUNICIPIO, NUMERO_PARTIDO),
    FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO (ID_MUNICIPIO),
    FOREIGN KEY (NUMERO_PARTIDO) REFERENCES PARTIDO (NUMERO_PARTIDO)
);