CREATE SEQUENCE DEPTID_SEQ
    INCREMENT BY 10
    START WITH 500
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
    
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
VALUES (DEPTID_SEQ.NEXTVAL, 'Support', 2500);

SELECT * FROM DEPARTMENTS;

SELECT DEPTID_SEQ.CURRVAL FROM DUAL;

CREATE SEQUENCE SEQ_TESTE
    START WITH 5
    INCREMENT BY -1
    MAXVALUE 5
    MINVALUE 0
    NOCACHE
    CYCLE;
    
SELECT DEPTID_SEQ.NEXTVAL FROM DUAL;

ALTER SEQUENCE DEPTID_SEQ
    INCREMENT BY 5
    MAXVALUE 99999
    CACHE 10
    NOCYCLE;

DROP SEQUENCE DEPTID_SEQ;

CREATE SYNONYM OFFICES FOR LOCATIONS;

SELECT * FROM OFFICES;

DROP SYNONYM OFFICES;

CREATE INDEX EMP_LAST_NAME_IDX ON EMPLOYEES(LAST_NAME);

DROP INDEX EMP_LAST_NAME_IDX;