CREATE TABLE FUNCIONARIO(
    COD_FUNC INT PRIMARY KEY,
    NOME VARCHAR2(30),
    SALARIO NUMBER(10, 2) );
    
INSERT INTO FUNCIONARIO VALUES(1, 'leal', 100);
SELECT * FROM FUNCIONARIO;
SELECT * FROM USER2.EMP;

GRANT SELECT ON FUNCIONARIO TO TESTE;
GRANT INSERT ON FUNCIONARIO TO TESTE;

INSERT INTO FUNCIONARIO VALUES(3, 'Final', 300);

COMMIT;

UPDATE FUNCIONARIO SET NOME = 'Leal' WHERE COD_FUNC = 1;

GRANT SELECT, INSERT, UPDATE ON FUNCIONARIO TO USER2;
REVOKE ALL ON FUNCIONARIO FROM USER2;
    