--1
SELECT NOME_MUNICIPIO, SIGLA_PARTIDO, VOTOS
FROM MUNICIPIO INNER JOIN VOTOS USING (ID_MUNICIPIO)
RIGHT JOIN PARTIDO USING (NUMERO_PARTIDO);

--2
--Mostra o partido mais votado em um municipio e seu numero de votos
--Completo
SELECT NOME_MUNICIPIO AS "Município", SIGLA_PARTIDO AS "Partido mais votado", VOTOS AS "Votos"
FROM MUNICIPIO INNER JOIN VOTOS USING (ID_MUNICIPIO)
INNER JOIN PARTIDO USING(NUMERO_PARTIDO)
WHERE (ID_MUNICIPIO, VOTOS) IN (SELECT ID_MUNICIPIO, MAX(VOTOS) FROM VOTOS GROUP BY ID_MUNICIPIO);

--4
--Cria uma view que agrega todos os votos em um partido por estado
--Completo
CREATE OR REPLACE VIEW votos_por_estado AS SELECT NOME_UF AS UF, NOME_PARTIDO AS Partido, SUM(VOTOS) AS "Total de Votos"
FROM UF INNER JOIN MUNICIPIO USING (ID_UF)
INNER JOIN VOTOS USING(ID_MUNICIPIO)
INNER JOIN PARTIDO USING (NUMERO_PARTIDO)
GROUP BY NOME_UF, NOME_PARTIDO;

SELECT ID_MUNICIPIO, MAX(VOTOS) FROM VOTOS GROUP BY ID_MUNICIPIO;

SELECT * FROM votos_por_estado;

--5
--O usuário administrador estabelecido no exercício deve tirar a permissão delete de outro