ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

DROP USER USER1 CASCADE;
DROP USER USER2 CASCADE;

CREATE USER USER1 IDENTIFIED BY user1;
ALTER USER USER1 DEFAULT TABLESPACE USERS QUOTA 5M ON USERS TEMPORARY TABLESPACE TEMP;

CREATE USER USER2 IDENTIFIED BY user2;
ALTER USER USER2 DEFAULT TABLESPACE USERS QUOTA 5M ON USERS TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO USER1, USER2;