SET SERVEROUTPUT ON
--1
DECLARE
    CURSO VARCHAR(20) := 'ADS';
    NUM INT := 10;
    CONST CONSTANT NUMBER := 2026;
BEGIN
    DBMS_OUTPUT.PUT_LINE(CURSO ||' ' || NUM || ' ' || CONST);
END;
/

--2
--Permite declarar variáveis baseadas em colunas de tabelas já existentes, ou outras variáveis já declardas
DECLARE
    v_salario employees.salary%TYPE;
BEGIN
    SELECT MAX(salary) INTO v_salario FROM EMPLOYEES;
    DBMS_OUTPUT.PUT_LINE('$' || v_salario);
END;
/

--3
DECLARE
    NOME VARCHAR2(50);
BEGIN
    NOME := '&INPUT';
    DBMS_OUTPUT.PUT_LINE('Bem-vindo ao PL/SQL, ' || NOME);
END;
/

--4
DECLARE
    v_nome EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME INTO V_NOME FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 100;
    DBMS_OUTPUT.PUT_LINE(V_NOME);
END;
/

--5
--Muitas linhas
DECLARE
    v_nome EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME INTO V_NOME FROM EMPLOYEES;
    DBMS_OUTPUT.PUT_LINE(V_NOME);
END;
/
--Erro reportando número excessivo de linhas

--Sem linhas
DECLARE
    v_nome EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME INTO V_NOME FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 0;
    DBMS_OUTPUT.PUT_LINE(V_NOME);
END;
/
--Erro reportando que não foram encontrados dados

--6
DECLARE
    MIN_DATE EMPLOYEES.HIRE_DATE%TYPE;
    MAX_DATE MIN_DATE%TYPE;
BEGIN
    SELECT MIN(HIRE_DATE), MAX(HIRE_DATE) INTO MIN_DATE, MAX_DATE FROM EMPLOYEES;
    DBMS_OUTPUT.PUT_LINE('MIN: ' || MIN_DATE);
    DBMS_OUTPUT.PUT_LINE('MAX: ' || MAX_DATE);
END;
/

SELECT EMPLOYEE_ID, SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 80;
SELECT ROUND(AVG(SALARY), 2) FROM EMPLOYEES WHERE DEPARTMENT_ID = 80;

DECLARE     
    EMP_SAL EMPLOYEES.SALARY%TYPE;
    DEPTN0 EMPLOYEES.DEPARTMENT_ID%TYPE := 80;
    CURSOR C_EMP IS SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 80;
BEGIN
    FOR EMP IN C_EMP LOOP
        EMP_SAL := EMP.SALARY * 1.15;
        UPDATE EMPLOYEES
        SET SALARY = EMP_SAL
        WHERE EMPLOYEE_ID = EMP.EMPLOYEE_ID;
    END LOOP;
END;
/
