DROP USER USER1 CASCADE;
CREATE USER USER1 IDENTIFIED BY user1;
ALTER USER USER1 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA 20M ON USERS;

GRANT CREATE SESSION, CREATE TABLE TO USER1;

SELECT xid, status, start_time FROM V$TRANSACTION;
SELECT * FROM V$TRANSACTION;

DROP USER USER2 CASCADE;
DROP USER USER3 CASCADE;

CREATE USER USER2 IDENTIFIED BY user2;
ALTER USER USER2 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA 20M ON USERS;

GRANT CREATE SESSION, CREATE TABLE TO USER2;

CREATE USER USER3 IDENTIFIED BY user3;
ALTER USER USER3 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA 20M ON USERS;

GRANT CREATE SESSION, CREATE TABLE TO USER3;